[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd backend && npx prisma generate"]

[start]
cmd = "cd backend && npm start"
